src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
#[ORM\HasLifecycleCallbacks]

class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 120)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 80)]
    private ?string $author = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column]
    private ?bool $isPremium = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $publication_date = null;

  
    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->created_at = new \DateTimeImmutable();
        $this->setUpdatedAtValue();
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updated_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function isPremium(): ?bool
    {
        return $this->isPremium;
    }

    public function setPremium(bool $isPremium): static
    {
        $this->isPremium = $isPremium;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeImmutable
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeImmutable $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

 
}

templates/components/partials/articleCard.html.twig
<div class="grid grid-cols-1 gap-4 w-90 md:grid-cols-2">

	{% for article  in articles %}
		<!-- Title -->
		<div class="relative flex flex-col p-4 mb-4 border rounded-md shadow-lg md:p-6">

			<div class="flex items-center justify-between">
				<h2 class="mt-2 text-xl font-bold text-gray-500 transition-colors duration-300 hover:text-blue-500">
					{{ article.title }}
				</h2>
				{% if article.isPremium %}
					<span class="px-2 py-1 text-xs font-semibold text-white bg-yellow-500 rounded">Premium</span>

				{% endif %}
			</div>
			<!-- Premium Badge -->

			<span class="text-xs text-gray-500">By:
				{{ article.author }}</span>


			<!-- Publication Date -->
			<div class="mt-4">
				<span class="text-sm text-gray-500">
					Published on:
					{{ article.publicationDate|date('F j, Y') }}
				</span>
			</div>

			<div class="flex justify-end mt-4">
				{% if article.isPremium %}
					<a href="{{path('app_article_premium', {'id': article.id})}}" class="text-blue-500 bg-gray-400 border-2 rounded-md hover:underline border-voilet-950">Go Premium</a>
				{% else %}
					<a href="{{ path('app_article_show', {'id': article.id}) }}" class="text-blue-500 hover:underline">Read more</a>
				{% endif %}
			</div>
		</div>
	{% endfor %}

</div>

templates/components/partials/navbar.html.twig
<div class="flex p-4 text-4xl font-semibold text-center bg-white shadow-md justify-evenly">
	<ul
		class="flex items-center p-4 space-x-6">
		<!-- Logo -->
		<li>
			<a href="/">
				<img src="{{asset('img/logo.png')}}" alt="logo" class="w-8 h-8 transition-transform duration-200 ease-in-out rounded-full hover:scale-95">
			</a>
		</li>

		<!-- Navigation Links -->
		<div class="flex space-x-4">
			<li>
				<a href="/" class="text-gray-600 transition-colors duration-200 hover:text-blue-500">Home</a>
			</li>
			<li>
				<a href="#" class="text-gray-600 transition-colors duration-200 hover:text-blue-500">Articles</a>
			</li>
			<li>
				<a href="#" class="text-gray-600 transition-colors duration-200 hover:text-blue-500">Inscription</a>
			</li>
		</div>
	</ul>
</div>